package tests;

import static org.junit.Assert.*;

import org.junit.Test;

import task1.CaesarCipherBreaker;

public class TestCaesarCipher {

	/**
	 * Test Case Number 1
	 */
	@Test
	public void testCase1() {
		CaesarCipherBreaker ccb = new CaesarCipherBreaker();
		ccb.setCipherText("KWNJSIXMNUNXZSSJHJXXFWDQNPJUMNQTXTUMDQNPJFWYNYMFXSTXZWANAFQA"
				+ "FQZJWFYMJWNYNXTSJTKYMTXJYMNSLXBMNHMLNAJAFQZJYTXZWANAFQ");
		ccb.decipherText();
		assertEquals("5", ccb.getKey());
		assertEquals("FRIENDSHIPISUNNECESSARYLIKEPHILOSOPHYLIKEARTITHASNOSURVIVALVALUE"
				+ "RATHERITISONEOFTHOSETHINGSWHICHGIVEVALUETOSURVIVAL", ccb.getPlainText());
	}

	/**
	 * Test Case Number 2
	 */
	@Test
	public void testCase2() {
		CaesarCipherBreaker ccb = new CaesarCipherBreaker();
		ccb.setCipherText("DFNNPDDTDYZEQTYLWQLTWFCPTDYZEQLELWTETDESPNZFCLRPEZNZYETYFPESLENZFYED");
		ccb.decipherText();
		assertEquals("11", ccb.getKey());
		assertEquals("SUCCESSISNOTFINALFAILUREISNOTFATALITISTHECOURAGETOCONTINUETHATCOUNTS", ccb.getPlainText());
	}

	/**
	 * Test Case Number 3
	 */
	@Test
	public void testCase3() {
		CaesarCipherBreaker ccb = new CaesarCipherBreaker();
		ccb.setCipherText("DWZGDZQZOCVODHVBDIVODJIDNNOMJIBZMOCVIFIJRGZYBZOCVOHTOCDNHJMZKJOZIOOC"
				+ "VICDNOJMTOCVOYMZVHNVMZHJMZKJRZMAPGOCVIAVXONOCVOCJKZVGRVTNOMDPHKCNJQZMZSKZMDZI"
				+ "XZOCVOGVPBCOZMDNOCZJIGTXPMZAJMBMDZAVIYDWZGDZQZOCVOGJQZDNNOMJIBZMOCVIYZVOC");
		ccb.decipherText();
		assertEquals("21", ccb.getKey());
		assertEquals(
				"IBELIEVETHATIMAGINATIONISSTRONGERTHANKNOWLEDGETHATMYTHISMOREPOTENTTHANHISTORY"
						+ "THATDREAMSAREMOREPOWERFULTHANFACTSTHATHOPEALWAYSTRIUMPHSOVEREXPERIENCE"
						+ "THATLAUGHTERISTHEONLYCUREFORGRIEFANDIBELIEVETHATLOVEISSTRONGERTHANDEATH",
				ccb.getPlainText());
	}

	/**
	 * Test Case Number 4
	 */
	@Test
	public void testCase4() {
		CaesarCipherBreaker ccb = new CaesarCipherBreaker();
		ccb.setCipherText("SGDFNNCMDVRHRSGZSSGDLNLDMSXNTCDBHCDSGZSVGZSXNTJMNVHRLNQDHLONQSZMSSGZMVG"
				+ "ZSXNTGZUDADDMSZTFGSSNADKHDUDXNTVHKKGZUDRGHESDCFDZQRHMXNTQPTDRSENQZATMCZMBDRTBBD"
				+ "RRBNLDREQNLVHSGHMMNSEQNLVHSGNTS");
		ccb.decipherText();
		assertEquals("25", ccb.getKey());
		assertEquals("THEGOODNEWSISTHATTHEMOMENTYOUDECIDETHATWHATYOUKNOWISMOREIMPORTANTTHANWHATYOU"
				+ "HAVEBEENTAUGHTTOBELIEVEYOUWILLHAVESHIFTEDGEARSINYOURQUESTFORABUNDANCESUCCESSCOMES"
				+ "FROMWITHINNOTFROMWITHOUT", ccb.getPlainText());
	}

	/**
	 * Test Case Number 5
	 * 
	 */
	@Test
	public void testCase5() {
		CaesarCipherBreaker ccb = new CaesarCipherBreaker();
		ccb.setCipherText("PERFECTIONISMISTHEENEMYOFHAPPINESSEMBRACEBEINGPERFECTLYIMPERFECTLEARN"
				+ "FROMYOURMISTAKESANDFORGIVEYOURSELFYOUWILLBEHAPPIERWEMAKEMISTAKESBECAUSEWEARE"
				+ "IMPERFECTLEARNFROMYOURMISTAKESFORGIVEYOURSELFANDKEEPMOVINGFORWARD");
		ccb.decipherText();
		assertEquals("0", ccb.getKey());
		assertEquals("PERFECTIONISMISTHEENEMYOFHAPPINESSEMBRACEBEINGPERFECTLYIMPERFECTLEARN"
				+ "FROMYOURMISTAKESANDFORGIVEYOURSELFYOUWILLBEHAPPIERWEMAKEMISTAKESBECAUSEWEARE"
				+ "IMPERFECTLEARNFROMYOURMISTAKESFORGIVEYOURSELFANDKEEPMOVINGFORWARD", ccb.getPlainText());
	}

}
